package cn.edu.zafu.openfiredemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.edu.zafu.openfiredemo.im.db.bean.ChatRecord;

import cn.edu.zafu.openfiredemo.greendao.ChatRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRecordDaoConfig;

    private final ChatRecordDao chatRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);

        registerDao(ChatRecord.class, chatRecordDao);
    }
    
    public void clear() {
        chatRecordDaoConfig.clearIdentityScope();
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

}
